//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Reservaciones.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaReservacionEntities : DbContext
    {
        public SistemaReservacionEntities()
            : base("name=SistemaReservacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
    
        public virtual ObjectResult<Nullable<int>> ConsultarCapacidad(Nullable<int> p_idReservacion, Nullable<int> p_idHotel)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            var p_idHotelParameter = p_idHotel.HasValue ?
                new ObjectParameter("P_idHotel", p_idHotel) :
                new ObjectParameter("P_idHotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConsultarCapacidad", p_idReservacionParameter, p_idHotelParameter);
        }
    
        public virtual int proc_AgregarUsuario(string p_nombreCompleto, string p_email, string p_clave, string p_esEmpleado, string p_estado)
        {
            var p_nombreCompletoParameter = p_nombreCompleto != null ?
                new ObjectParameter("P_nombreCompleto", p_nombreCompleto) :
                new ObjectParameter("P_nombreCompleto", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("P_email", p_email) :
                new ObjectParameter("P_email", typeof(string));
    
            var p_claveParameter = p_clave != null ?
                new ObjectParameter("P_clave", p_clave) :
                new ObjectParameter("P_clave", typeof(string));
    
            var p_esEmpleadoParameter = p_esEmpleado != null ?
                new ObjectParameter("P_esEmpleado", p_esEmpleado) :
                new ObjectParameter("P_esEmpleado", typeof(string));
    
            var p_estadoParameter = p_estado != null ?
                new ObjectParameter("P_estado", p_estado) :
                new ObjectParameter("P_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_AgregarUsuario", p_nombreCompletoParameter, p_emailParameter, p_claveParameter, p_esEmpleadoParameter, p_estadoParameter);
        }
    
        public virtual int proc_CancelarBitacora(Nullable<int> p_idReservacion, Nullable<int> p_idPersona)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            var p_idPersonaParameter = p_idPersona.HasValue ?
                new ObjectParameter("P_idPersona", p_idPersona) :
                new ObjectParameter("P_idPersona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CancelarBitacora", p_idReservacionParameter, p_idPersonaParameter);
        }
    
        public virtual int proc_CancelarReservacion(Nullable<int> p_idReservacion)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CancelarReservacion", p_idReservacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_ConseguirID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_ConseguirID");
        }
    
        public virtual ObjectResult<proc_ConsultarCliente_Result> proc_ConsultarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarCliente_Result>("proc_ConsultarCliente");
        }
    
        public virtual ObjectResult<proc_ConsultarDetalleBitacora_Result> proc_ConsultarDetalleBitacora(Nullable<int> p_idReservacion)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarDetalleBitacora_Result>("proc_ConsultarDetalleBitacora", p_idReservacionParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarDetalleReservacion_Result> proc_ConsultarDetalleReservacion(Nullable<int> p_idReservacion)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarDetalleReservacion_Result>("proc_ConsultarDetalleReservacion", p_idReservacionParameter);
        }
    
        public virtual ObjectResult<string> proc_ConsultarEstadoReservacion(Nullable<int> p_idReservacion)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_ConsultarEstadoReservacion", p_idReservacionParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarFecha_Result> proc_ConsultarFecha(Nullable<int> p_idReservacion)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarFecha_Result>("proc_ConsultarFecha", p_idReservacionParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarFechaReservacion_Result> proc_ConsultarFechaReservacion(Nullable<int> p_idHabitacion)
        {
            var p_idHabitacionParameter = p_idHabitacion.HasValue ?
                new ObjectParameter("P_idHabitacion", p_idHabitacion) :
                new ObjectParameter("P_idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarFechaReservacion_Result>("proc_ConsultarFechaReservacion", p_idHabitacionParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarHabitaciones_Result> proc_ConsultarHabitaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarHabitaciones_Result>("proc_ConsultarHabitaciones");
        }
    
        public virtual ObjectResult<proc_ConsultarHabitacionPorId_Result> proc_ConsultarHabitacionPorId(Nullable<int> p_idHabitacion)
        {
            var p_idHabitacionParameter = p_idHabitacion.HasValue ?
                new ObjectParameter("P_idHabitacion", p_idHabitacion) :
                new ObjectParameter("P_idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarHabitacionPorId_Result>("proc_ConsultarHabitacionPorId", p_idHabitacionParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarHotel_Result> proc_ConsultarHotel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarHotel_Result>("proc_ConsultarHotel");
        }
    
        public virtual ObjectResult<proc_ConsultarHotelPorId_Result> proc_ConsultarHotelPorId(Nullable<int> p_idHotel)
        {
            var p_idHotelParameter = p_idHotel.HasValue ?
                new ObjectParameter("P_idHotel", p_idHotel) :
                new ObjectParameter("P_idHotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarHotelPorId_Result>("proc_ConsultarHotelPorId", p_idHotelParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarReservaciones_Result> proc_ConsultarReservaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarReservaciones_Result>("proc_ConsultarReservaciones");
        }
    
        public virtual ObjectResult<proc_ConsultarReservacionPorID_Result> proc_ConsultarReservacionPorID(Nullable<int> p_idReservacion)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarReservacionPorID_Result>("proc_ConsultarReservacionPorID", p_idReservacionParameter);
        }
    
        public virtual ObjectResult<proc_ConsultarUsuarioReservaciones_Result> proc_ConsultarUsuarioReservaciones(string p_nombre)
        {
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("P_nombre", p_nombre) :
                new ObjectParameter("P_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ConsultarUsuarioReservaciones_Result>("proc_ConsultarUsuarioReservaciones", p_nombreParameter);
        }
    
        public virtual int proc_CorregirBitacora(Nullable<int> p_idReservacion, Nullable<int> p_idPersona)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            var p_idPersonaParameter = p_idPersona.HasValue ?
                new ObjectParameter("P_idPersona", p_idPersona) :
                new ObjectParameter("P_idPersona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CorregirBitacora", p_idReservacionParameter, p_idPersonaParameter);
        }
    
        public virtual int proc_CrearBitacora(Nullable<int> p_idReservacion, Nullable<int> p_idPersona)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            var p_idPersonaParameter = p_idPersona.HasValue ?
                new ObjectParameter("P_idPersona", p_idPersona) :
                new ObjectParameter("P_idPersona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CrearBitacora", p_idReservacionParameter, p_idPersonaParameter);
        }
    
        public virtual int proc_CrearHabitacion(Nullable<int> p_idHotel, string p_numeroHabitacion, Nullable<int> p_capacidadMaxima, string p_descripcion)
        {
            var p_idHotelParameter = p_idHotel.HasValue ?
                new ObjectParameter("P_idHotel", p_idHotel) :
                new ObjectParameter("P_idHotel", typeof(int));
    
            var p_numeroHabitacionParameter = p_numeroHabitacion != null ?
                new ObjectParameter("P_numeroHabitacion", p_numeroHabitacion) :
                new ObjectParameter("P_numeroHabitacion", typeof(string));
    
            var p_capacidadMaximaParameter = p_capacidadMaxima.HasValue ?
                new ObjectParameter("P_capacidadMaxima", p_capacidadMaxima) :
                new ObjectParameter("P_capacidadMaxima", typeof(int));
    
            var p_descripcionParameter = p_descripcion != null ?
                new ObjectParameter("P_descripcion", p_descripcion) :
                new ObjectParameter("P_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CrearHabitacion", p_idHotelParameter, p_numeroHabitacionParameter, p_capacidadMaximaParameter, p_descripcionParameter);
        }
    
        public virtual int proc_CrearReservacion(Nullable<int> p_idPersona, Nullable<int> p_idHabitacion, Nullable<System.DateTime> p_fechaEntrada, Nullable<System.DateTime> p_fechaSalida, Nullable<int> p_numeroAdultos, Nullable<int> p_numeroNinho, Nullable<int> p_totalDiasReservacion, Nullable<decimal> p_costoPorCadaAdulto, Nullable<decimal> p_costoPorCadaNinho, Nullable<decimal> p_costoTotal)
        {
            var p_idPersonaParameter = p_idPersona.HasValue ?
                new ObjectParameter("P_idPersona", p_idPersona) :
                new ObjectParameter("P_idPersona", typeof(int));
    
            var p_idHabitacionParameter = p_idHabitacion.HasValue ?
                new ObjectParameter("P_idHabitacion", p_idHabitacion) :
                new ObjectParameter("P_idHabitacion", typeof(int));
    
            var p_fechaEntradaParameter = p_fechaEntrada.HasValue ?
                new ObjectParameter("P_fechaEntrada", p_fechaEntrada) :
                new ObjectParameter("P_fechaEntrada", typeof(System.DateTime));
    
            var p_fechaSalidaParameter = p_fechaSalida.HasValue ?
                new ObjectParameter("P_fechaSalida", p_fechaSalida) :
                new ObjectParameter("P_fechaSalida", typeof(System.DateTime));
    
            var p_numeroAdultosParameter = p_numeroAdultos.HasValue ?
                new ObjectParameter("P_numeroAdultos", p_numeroAdultos) :
                new ObjectParameter("P_numeroAdultos", typeof(int));
    
            var p_numeroNinhoParameter = p_numeroNinho.HasValue ?
                new ObjectParameter("P_numeroNinho", p_numeroNinho) :
                new ObjectParameter("P_numeroNinho", typeof(int));
    
            var p_totalDiasReservacionParameter = p_totalDiasReservacion.HasValue ?
                new ObjectParameter("P_totalDiasReservacion", p_totalDiasReservacion) :
                new ObjectParameter("P_totalDiasReservacion", typeof(int));
    
            var p_costoPorCadaAdultoParameter = p_costoPorCadaAdulto.HasValue ?
                new ObjectParameter("P_costoPorCadaAdulto", p_costoPorCadaAdulto) :
                new ObjectParameter("P_costoPorCadaAdulto", typeof(decimal));
    
            var p_costoPorCadaNinhoParameter = p_costoPorCadaNinho.HasValue ?
                new ObjectParameter("P_costoPorCadaNinho", p_costoPorCadaNinho) :
                new ObjectParameter("P_costoPorCadaNinho", typeof(decimal));
    
            var p_costoTotalParameter = p_costoTotal.HasValue ?
                new ObjectParameter("P_costoTotal", p_costoTotal) :
                new ObjectParameter("P_costoTotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CrearReservacion", p_idPersonaParameter, p_idHabitacionParameter, p_fechaEntradaParameter, p_fechaSalidaParameter, p_numeroAdultosParameter, p_numeroNinhoParameter, p_totalDiasReservacionParameter, p_costoPorCadaAdultoParameter, p_costoPorCadaNinhoParameter, p_costoTotalParameter);
        }
    
        public virtual int proc_EditarHabitacion(Nullable<int> p_idHabitacion, string p_numeroHabitacion, Nullable<int> p_capacidadMaxima, string p_descripcion)
        {
            var p_idHabitacionParameter = p_idHabitacion.HasValue ?
                new ObjectParameter("P_idHabitacion", p_idHabitacion) :
                new ObjectParameter("P_idHabitacion", typeof(int));
    
            var p_numeroHabitacionParameter = p_numeroHabitacion != null ?
                new ObjectParameter("P_numeroHabitacion", p_numeroHabitacion) :
                new ObjectParameter("P_numeroHabitacion", typeof(string));
    
            var p_capacidadMaximaParameter = p_capacidadMaxima.HasValue ?
                new ObjectParameter("P_capacidadMaxima", p_capacidadMaxima) :
                new ObjectParameter("P_capacidadMaxima", typeof(int));
    
            var p_descripcionParameter = p_descripcion != null ?
                new ObjectParameter("P_descripcion", p_descripcion) :
                new ObjectParameter("P_descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_EditarHabitacion", p_idHabitacionParameter, p_numeroHabitacionParameter, p_capacidadMaximaParameter, p_descripcionParameter);
        }
    
        public virtual int proc_EditarReservacion(Nullable<int> p_idReservacion, Nullable<System.DateTime> p_fechaEntrada, Nullable<System.DateTime> p_fechaSalida, Nullable<int> p_numeroAdultos, Nullable<int> p_numeroNinho, Nullable<int> p_totalDiasReservacion, Nullable<decimal> p_costoPorCadaAdulto, Nullable<decimal> p_costoPorCadaNinho, Nullable<decimal> p_costoTotal)
        {
            var p_idReservacionParameter = p_idReservacion.HasValue ?
                new ObjectParameter("P_idReservacion", p_idReservacion) :
                new ObjectParameter("P_idReservacion", typeof(int));
    
            var p_fechaEntradaParameter = p_fechaEntrada.HasValue ?
                new ObjectParameter("P_fechaEntrada", p_fechaEntrada) :
                new ObjectParameter("P_fechaEntrada", typeof(System.DateTime));
    
            var p_fechaSalidaParameter = p_fechaSalida.HasValue ?
                new ObjectParameter("P_fechaSalida", p_fechaSalida) :
                new ObjectParameter("P_fechaSalida", typeof(System.DateTime));
    
            var p_numeroAdultosParameter = p_numeroAdultos.HasValue ?
                new ObjectParameter("P_numeroAdultos", p_numeroAdultos) :
                new ObjectParameter("P_numeroAdultos", typeof(int));
    
            var p_numeroNinhoParameter = p_numeroNinho.HasValue ?
                new ObjectParameter("P_numeroNinho", p_numeroNinho) :
                new ObjectParameter("P_numeroNinho", typeof(int));
    
            var p_totalDiasReservacionParameter = p_totalDiasReservacion.HasValue ?
                new ObjectParameter("P_totalDiasReservacion", p_totalDiasReservacion) :
                new ObjectParameter("P_totalDiasReservacion", typeof(int));
    
            var p_costoPorCadaAdultoParameter = p_costoPorCadaAdulto.HasValue ?
                new ObjectParameter("P_costoPorCadaAdulto", p_costoPorCadaAdulto) :
                new ObjectParameter("P_costoPorCadaAdulto", typeof(decimal));
    
            var p_costoPorCadaNinhoParameter = p_costoPorCadaNinho.HasValue ?
                new ObjectParameter("P_costoPorCadaNinho", p_costoPorCadaNinho) :
                new ObjectParameter("P_costoPorCadaNinho", typeof(decimal));
    
            var p_costoTotalParameter = p_costoTotal.HasValue ?
                new ObjectParameter("P_costoTotal", p_costoTotal) :
                new ObjectParameter("P_costoTotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_EditarReservacion", p_idReservacionParameter, p_fechaEntradaParameter, p_fechaSalidaParameter, p_numeroAdultosParameter, p_numeroNinhoParameter, p_totalDiasReservacionParameter, p_costoPorCadaAdultoParameter, p_costoPorCadaNinhoParameter, p_costoTotalParameter);
        }
    
        public virtual ObjectResult<proc_FiltroReservaciones_Result> proc_FiltroReservaciones(Nullable<int> p_idPersona, Nullable<System.DateTime> p_fechaEntrada, Nullable<System.DateTime> p_fechaSalida)
        {
            var p_idPersonaParameter = p_idPersona.HasValue ?
                new ObjectParameter("P_idPersona", p_idPersona) :
                new ObjectParameter("P_idPersona", typeof(int));
    
            var p_fechaEntradaParameter = p_fechaEntrada.HasValue ?
                new ObjectParameter("P_fechaEntrada", p_fechaEntrada) :
                new ObjectParameter("P_fechaEntrada", typeof(System.DateTime));
    
            var p_fechaSalidaParameter = p_fechaSalida.HasValue ?
                new ObjectParameter("P_fechaSalida", p_fechaSalida) :
                new ObjectParameter("P_fechaSalida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_FiltroReservaciones_Result>("proc_FiltroReservaciones", p_idPersonaParameter, p_fechaEntradaParameter, p_fechaSalidaParameter);
        }
    
        public virtual int proc_Inactivar(Nullable<int> p_idHabitacion)
        {
            var p_idHabitacionParameter = p_idHabitacion.HasValue ?
                new ObjectParameter("P_idHabitacion", p_idHabitacion) :
                new ObjectParameter("P_idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Inactivar", p_idHabitacionParameter);
        }
    
        public virtual ObjectResult<proc_ValidarUsuario_Result> proc_ValidarUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ValidarUsuario_Result>("proc_ValidarUsuario");
        }
    }
}
